//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _102210014_LeDucKhoa_bt06
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LSH()
        {
            this.SVs = new HashSet<SV>();
        }
    
        public int IDLop { get; set; }
        public string NameLop { get; set; }
        public override string ToString()
        {
            return NameLop;
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SV> SVs { get; set; }
    }
}
