//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _102210014_LeDucKhoa_bt06
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV
    {
        public string MSSV { get; set; }
        public string Name { get; set; }
        public int ID_Lop { get; set; }
        public System.DateTime NS { get; set; }
        public double DTB { get; set; }
        public bool Gender { get; set; }
        public bool Anh { get; set; }
        public bool HocBa { get; set; }
        public bool CCCD { get; set; }
    
        public virtual LSH LSH { get; set; }
    }
}
